steps:
  - command: |
      # set up environment
      source /etc/environment
      export ANASYMOD_PYTHON=python3.7
      export FPGA_SERVER=1
      printenv

      # run regression script
      source regress.sh
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
      fpga_verif: "true"