steps:
  - command: |
      # set up environment
      source /etc/environment
      python3.7 -m venv venv
      source venv/bin/activate
      printenv

      # upgrade pip
      python -m pip install --upgrade pip

      # run regression script
      source regress.sh
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
      fpga_verif: "true"
