steps:
  - command: |
      # set up environment
      source /etc/environment
      export FPGA_SERVER=1
      export ANASYMOD_TARGET=sim_vivado
      printenv

      # set up Python environment
      python3.7 -m venv venv
      source venv/bin/activate

      # run regression script
      source regress.sh
    label: "test_emu"
    timeout_in_minutes: 60
    artifact_paths:
      - "tests/*/build/*/prj/prj.runs/*/*.bit"
      - "tests/*/build/*/prj/prj.runs/*/*.ltx"
      - "tests/*/build/*/prj/prj.runs/*/*.log"
      - "tests/*/build/*/prj/prj.sim/*/behav/xsim/*.log"
      - "tests/*/build/*/prj/prj.sim/*/behav/xsim/*.sh"
      - "tests/*/build/*/prj/prj.runs/*/*.xsa"
      - "tests/*/build/*/prj/prj.runs/*/ps7_init.tcl"
      - "tests/*/build/*/prj/prj.sdk/*/*/*.elf"
      - "tests/*/build/*/*.tcl"
    agents:
      fpga_verif: "true"