steps:
  - label: "test"
    command: |
      # set up environment
      source /cad/modules/tcl/init/bash
      module load base xcelium/19.03.003
      export ANASYMOD_TARGET=sim_xcelium
      printenv

      # set up Python environment
      /usr/local/miniconda/bin/python3.7 -m venv venv
      source venv/bin/activate

      # run regression script
      source regress.sh
    timeout_in_minutes: 60
    agents:
      fault2: "true"
  - label: "test_emu"
    command: |
      # set up environment
      source /etc/environment
      export FPGA_SERVER=1
      export ANASYMOD_TARGET=sim_vivado
      printenv

      # set up Python environment
      python3.7 -m venv venv
      source venv/bin/activate

      # update the board name to match what is
      # available on the regression server
      sed -i 's/PYNQ_Z1/ZC702/g' unittests/*/prj.yaml

      # run regression script
      source regress.sh
    artifact_paths:
      - "unittests/*/build/*/prj/prj.runs/*/*.bit"
      - "unittests/*/build/*/prj/prj.runs/*/*.ltx"
      - "unittests/*/build/*/prj/prj.runs/*/*.log"
      - "unittests/*/build/*/prj/prj.sim/*/behav/xsim/*.log"
      - "unittests/*/build/*/prj/prj.sim/*/behav/xsim/*.sh"
      - "unittests/*/build/*/prj/prj.runs/*/*.xsa"
      - "unittests/*/build/*/prj/prj.runs/*/ps7_init.tcl"
      - "unittests/*/build/*/prj/prj.sdk/*/*/*.elf"
      - "unittests/*/build/*/*.tcl"
      - "unittests/*/prj.y*ml"
    timeout_in_minutes: 60
    agents:
      fpga_verif: "true"
