steps:
  - command: |
      # set up environment
      source /etc/environment
      echo $$PATH

      # create virtual environment
      python3.7 -m venv venv
      source venv/bin/activate

      # upgrade pip
      pip install -U pip

      # install various python dependencies
      pip install wheel
      pip install pytest pytest-cov

      # install anasymod
      pip install -e .

      # specify python location (needed for msdsl)
      export PYTHON_MSDSL=`which python`
      echo $$PYTHON_MSDSL

      # run tests
      pytest --cov-report=xml --cov=anasymod tests -v -r s

      # upload coverage information
      bash <(curl -s https://codecov.io/bash)

      # deactivate virtual environment
      deactivate
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
      fpga_verif: "true"
