name: Regression

on:
  push:
  pull_request:
  schedule:
  - cron: 0 11 * * ?

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: sudo apt-get install iverilog
    - name: Run regression test
      run: source regress.sh
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        ANASYMOD_PYTHON: python3.7

  mac:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        brew install icarus-verilog
    - name: Run regression test
      run: source regress.sh
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        ANASYMOD_PYTHON: python3.7

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -L https://github.com/sgherbst/anasymod/releases/download/bogus/iverilog-v11-20201123-x64.tar.gz > iverilog-v11-20201123-x64.tar.gz
        tar xzvf iverilog-v11-20201123-x64.tar.gz
        echo `realpath iverilog/bin` >> $GITHUB_PATH
      shell: bash
    - name: Run regression test
      run: |
        iverilog/bin/iverilog.exe -V
        iverilog/bin/iverilog.exe -h
        source regress.sh
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        ANASYMOD_PYTHON: python3.7
      shell: bash
